name: Build Resume PDF

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image and extract PDF
        run: |
          
          cd examples
          # Build the image
          docker build -t cv-builder --platform linux/amd64 .
          
          # Create a container (so we can copy from it)
          docker create --name cv-container --platform linux/amd64 cv-builder
          
          # Copy the compiled PDF out to the 'output' directory
          docker cp cv-container:/resume/out/resume.pdf ./cv_out.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resume-PDF
          path: ./examples/cv_out.pdf
          if-no-files-found: error

      - name: Release PDF
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          files: ./examples/cv_out.pdf
          tag_name: latest
          body: "Automatically generated resume from the latest commit."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}